# Generated by Django 3.0.5 on 2021-02-21 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210221_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_add',
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 11, 2, 50, 446938, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 11, 2, 50, 445936, tzinfo=utc)),
        ),
    ]
