# Generated by Django 3.0.5 on 2021-02-21 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20210221_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 17, 58, 54, 634301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 17, 58, 54, 635304, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.User')),
            ],
        ),
    ]
